package com.smy.weitu.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.smy.weitu.model.WeiTuRecord;

import com.smy.weitu.model.WeiTuRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weiTuRecordDaoConfig;

    private final WeiTuRecordDao weiTuRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weiTuRecordDaoConfig = daoConfigMap.get(WeiTuRecordDao.class).clone();
        weiTuRecordDaoConfig.initIdentityScope(type);

        weiTuRecordDao = new WeiTuRecordDao(weiTuRecordDaoConfig, this);

        registerDao(WeiTuRecord.class, weiTuRecordDao);
    }
    
    public void clear() {
        weiTuRecordDaoConfig.getIdentityScope().clear();
    }

    public WeiTuRecordDao getWeiTuRecordDao() {
        return weiTuRecordDao;
    }

}
