package com.smy.weitu.model;

import java.util.Date;

import android.os.Parcel;
import android.os.Parcelable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WEI_TU_RECORD.
 */
public class WeiTuRecord implements Parcelable{
    private String uri;
    private java.util.Date time;
    private Long longitude;
    private Long latitude;
    private Boolean exists;
    private String markerPast;
    private String markerNow;
    private String msg;

    public WeiTuRecord() {
    }
    public WeiTuRecord(Parcel parcel){
    	uri = parcel.readString();
    	time = (Date) (parcel.readSerializable());
    	longitude = parcel.readLong();
    	latitude = parcel.readLong();
    	markerPast = parcel.readString();
    	markerNow = parcel.readString();
    	msg = parcel.readString();
    }

    public WeiTuRecord(String uri) {
        this.uri = uri;
    }

    public WeiTuRecord(String uri, java.util.Date time, Long longitude, Long latitude, Boolean exists, String markerPast, String markerNow, String msg) {
        this.uri = uri;
        this.time = time;
        this.longitude = longitude;
        this.latitude = latitude;
        this.exists = exists;
        this.markerPast = markerPast;
        this.markerNow = markerNow;
        this.msg = msg;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Long getLongitude() {
        return longitude;
    }

    public void setLongitude(Long longitude) {
        this.longitude = longitude;
    }

    public Long getLatitude() {
        return latitude;
    }

    public void setLatitude(Long latitude) {
        this.latitude = latitude;
    }

    public Boolean getExists() {
        return exists;
    }

    public void setExists(Boolean exists) {
        this.exists = exists;
    }

    public String getMarkerPast() {
        return markerPast;
    }

    public void setMarkerPast(String markerPast) {
        this.markerPast = markerPast;
    }

    public String getMarkerNow() {
        return markerNow;
    }

    public void setMarkerNow(String markerNow) {
        this.markerNow = markerNow;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

	@Override
	public int describeContents() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		// TODO Auto-generated method stub
		dest.writeString(uri);
		dest.writeSerializable(time);
		dest.writeLong(longitude);
		dest.writeLong(latitude);
		dest.writeString(markerPast);
		dest.writeString(markerNow);
		dest.writeString(msg);
	}
	
	public final static Parcelable.Creator<WeiTuRecord> CREATOR = new Parcelable.Creator<WeiTuRecord>() {

		@Override
		public WeiTuRecord createFromParcel(Parcel source) {
			// TODO Auto-generated method stub
			return new WeiTuRecord(source);
		}

		@Override
		public WeiTuRecord[] newArray(int size) {
			// TODO Auto-generated method stub
			return new WeiTuRecord[size];
		}
		
	};

}
